steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - worker/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/tracker/worker:v1
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/tracker/worker:v1
timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
